bonsai/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("oplaty.urls", namespace='oplaty')),
]

oplaty/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
    home_view,
    month_detail_view,
    year_detail_view,
    expense_create_view,
    expense_detail_view,
    expense_update_view,
    expense_delete_view,
    transaction_create_view,
    transaction_detail_view,
    transaction_update_view,
    transaction_delete_view,
    transaction_list_view,
    )

urlpatterns = [
    url(r'^$', home_view, name='home'),
    url(r'^(?P<year>\d{4})/$', year_detail_view, name='year-view'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', month_detail_view, name='month-view'),
    url(r'^expense/add/$', expense_create_view, name='expense-create'),
    url(r'^expense/(?P<id>\d+)/$', expense_detail_view, name='expense-detail'),
    url(r'^expense/(?P<id>\d+)/edit/$', expense_update_view, name='expense-update'),
    url(r'^expense/(?P<id>\d+)/delete/$', expense_delete_view, name='expense-delete'),
    url(r'^transaction/add/$', transaction_create_view, name='transaction-create'),
    url(r'^transaction/(?P<id>\d+)/$', transaction_detail_view, name='transaction-detail'),
    url(r'^transaction/(?P<id>\d+)/edit/$', transaction_update_view, name='transaction-update'),
    url(r'^transaction/(?P<id>\d+)/delete/$', transaction_delete_view, name='transaction-delete'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/transactions/$', transaction_list_view, name='transaction-list'),
]

oplaty/models.py
from django.conf import settings
from django.db import models
from django.db.models import Count, Avg

import calendar
from datetime import datetime, date

class ExpensesManager(models.Manager):
    def month_summary(self, month, year):
        data = {}
        expenses = self.by_month(month=month, year=year)
        recurring = expenses.filter(recurring=True)
        non_recurring = expenses.filter(recurring=False)

        data["recurring_amount_sum"] = sum([e.amount for e in recurring])
        data["recurring_remaining_sum"] = sum([e.remaining_amount for e in recurring])
        data["recurring_amount_paid_sum"] = sum([e.amount_paid for e in recurring])

        data["non_recurring_amount_sum"] = sum([e.amount for e in non_recurring])
        data["non_recurring_remaining_sum"] = sum([e.remaining_amount for e in non_recurring])
        data["non_recurring_amount_paid_sum"] = sum([e.amount_paid for e in non_recurring])

        data["total_amount_sum"] = sum([e.amount for e in expenses])
        data["total_remaining_sum"] = sum([e.remaining_amount for e in expenses])
        data["total_amount_paid_sum"] = sum([e.amount_paid for e in expenses])
        return data

    # def year_by_months(self, year):
    #     months = []
    #     for month in range(1, 13):
    #         months.append(Expense.objects.filter(due_date__month=month, due_date__year=year))
    #     return months

    def year_summary_by_months(self, year):
        return [self.month_summary(month=month, year=year) for month in range(1, 13)]

    def by_month(self, month, year):
        """Returns QS of all expenses fitlered by month and year"""
        return super().get_queryset().filter(due_date__month=month,due_date__year=year)

    def _ordered_titles(self, year, month=None):
        """Split and order expenses' TITLES by recurring and non-recurring,
           * (recurring) ordered by highest average amount,
           * (non-recurring) ordered by most frequent,
           returns: dict {"recurring":[title1, titl2, ...],
                         "non_recurring":[title1, title2, ...]}
        """
        if month:
            expenses = Expense.objects.filter(due_date__month=month, due_date__year=year)
        else:
            expenses = Expense.objects.filter(due_date__year=year)

        non_recurring_order = expenses.filter(recurring=False).values_list('title', flat=True).annotate(title_count=Count('title')).order_by('-title_count')
        recurring_titles = set(expenses.filter(recurring=True).values_list('title', flat=True))
        recurring_avgs_order = {title: expenses.filter(title=title).aggregate(Avg('amount'))['amount__avg'] for title in recurring_titles}
        recurring_avgs_order = sorted(recurring_avgs_order.items(), key=lambda kv: kv[1],  reverse=True)
        recurring_avgs_order = [tup[0] for tup in recurring_avgs_order]

        return {"recurring":recurring_avgs_order, "non_recurring":non_recurring_order}

    def year_ordered(self, year):
        """- list of recurring and non-recurring expenses
           * (recurring) ordered by highest average amount
           * (non-recurring) ordered by most frequent
           * as a list of amounts for each month from Jan
         returns: dict:
            "recurring":[{"title":"expense_title_1","months":[exp1, None..exp2]}, ..],
            (same for non-recurring)
        """
        titles = self._ordered_titles(year=year)

        recurring_ordered = []
        for title in titles["recurring"]:
            data = {"title":title, "months":[]}
            for month in range(1, 13):
                try:
                    data["months"].append(Expense.objects.get(title=title, due_date__month=month, due_date__year=year))
                except Expense.DoesNotExist:
                    data["months"].append(None)
            recurring_ordered.append(data)

        non_recurring_ordered = []
        for title in titles["non_recurring"]:
            data = {"title":title, "months":[]}
            for month in range(1, 13):
                try:
                    data["months"].append(Expense.objects.get(title=title, due_date__month=month, due_date__year=year))
                except Expense.DoesNotExist:
                    data["months"].append(None)
            non_recurring_ordered.append(data)

        return {"recurring":recurring_ordered, "non_recurring":non_recurring_ordered}

    def month_ordered(self, month, year):
        titles = self._ordered_titles(month=month, year=year)
        recurring = [Expense.objects.get(title=title, due_date__month=month, due_date__year=year) for title in titles["recurring"]]
        non_recurring = [Expense.objects.get(title=title, due_date__month=month, due_date__year=year) for title in titles["non_recurring"]]
        return {"recurring":recurring, "non_recurring":non_recurring}

class Expense(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(null=False, blank=True)
    recurring = models.BooleanField(default=False)
    due_date = models.DateField(null=False, default=datetime.today)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = ExpensesManager()

    def __str__(self):
        return "{} {}".format(self.due_date, self.title)

    class Meta:
        ordering = ["-due_date"]
        unique_together = ('user', 'title', 'due_date')

    @property
    def amount_paid(self):
        transactions = Transaction.objects.filter(expense=self)
        return sum([t.amount for t in transactions])

    @property
    def remaining_amount(self):
        return self.amount_paid - self.amount


class TransationsManager(models.Manager):
    def by_month(self, month, year):
        return super().get_queryset().filter(date__month=month, date__year=year)

    def by_month_binded(self, month, year):
        expenses = Expense.objects.by_month(month=month, year=year)
        transactions = []
        tmp = [e.transactions.all() for e in expenses]
        [transactions.extend(v) for v in tmp]
        return transactions

    def month_sum_binded(self, month, year):
        transactions = self.by_month_binded(month=month, year=year)
        return sum([t.amount for t in transactions])

    def month_sum(self, month, year):
        transactions = self.by_month(month=month, year=year)
        return sum([t.amount for t in transactions])



class Transaction(models.Model):
    expense = models.ForeignKey(Expense, related_name='transactions', blank=False, null=False)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    comment = models.TextField(null=True, blank=True)
    date = models.DateField(default=datetime.today)

    objects = TransationsManager()

    def __str__(self):
        return "{} / {} ({})".format(self.date, self.amount, self.expense.title)

    #TODO: No idea how to get this to work??
    class Meta:
        ordering = ["-amount"]

oplaty/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import extras

from crispy_forms.helper import FormHelper

from datetime import date

from .models import (
    Transaction,
    Expense,
    )

class TransactionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    def clean_amount(self):
        amount = self.cleaned_data["amount"]
        if amount > 0:
            return amount
        else:
            raise ValidationError("Amount must be a positive number.")

    def clean_date(self):
        date = self.cleaned_data["date"]
        if date <= date.today():
            return date
        else:
            raise ValidationError("You can not add transaction in advance.")

    class Meta:
        model = Transaction
        fields = [
            "expense",
            "amount",
            "date",
            "comment",
        ]

        # widgets = {
        #     'date': extras.SelectDateWidget(attrs=({'style': 'width: 20%; display: inline-block;'}))
        # }

class ExpenseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    def clean_amount(self):
        amount = self.cleaned_data["amount"]
        if amount > 0:
            return amount
        else:
            raise ValidationError("Amount must be a positive number.")

    class Meta:
        #TODO: HOW TO PASS USER SILENTLY?
        model = Expense
        fields = [
            "title",
            "amount",
            "description",
            "recurring",
            "due_date",
        ]

oplaty/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from datetime import datetime
import calendar

from .forms import TransactionForm, ExpenseForm
from .models import Expense, Transaction

def transaction_create_view(request):
    form = TransactionForm(request.POST or None)
    context = {
        "form":form,
        "from":request.GET.get("from"),
        }
    if form.is_valid():
        form.save()
        messages.success(request, "Transaction successfully added.")
        previous_page = context["from"]
        if previous_page:
            return redirect(previous_page)
        context = {
            "form":TransactionForm(),
            }
    template = "oplaty/transaction-create-view.html"
    return render(request, template, context)

def transaction_detail_view(request, id=None):
        obj = get_object_or_404(Transaction, id=id)
        context = {
            "transaction":obj,
            "from":request.GET.get("from"),
            }
        template = "oplaty/transaction-detail-view.html"
        return render(request, template, context)

def transaction_update_view(request, id=None):
    obj = get_object_or_404(Transaction, id=id)
    form = TransactionForm(request.POST or None, instance=obj)
    context = {
        "form":form,
        "from":request.GET.get("from"),
        }
    if form.is_valid():
        form.save()
        messages.success(request, "Transaction saved.")
        previous_page = context["from"]
        print(previous_page)
        if previous_page:
            return redirect(previous_page)
        else:
            return redirect("oplaty:transaction-detail", id=id)
    template = "oplaty/transaction-update-view.html"
    return render(request, template, context)

def transaction_delete_view(request, id=None):
        obj = get_object_or_404(Transaction, id=id)
        context = {
        "transaction":obj,
        "from":request.GET.get("from"),
        }
        if request.method == "POST":
            obj.delete()
            messages.success(request, "Transaction successfully deleted.", extra_tags='alert')
            previous_page = context["from"]
            if previous_page:
                return redirect(previous_page)
            else:
                return redirect("oplaty:month-view", year=obj.expense.due_date.year,
                                                     month=obj.expense.due_date.month)
        template = "oplaty/transaction-delete-view.html"
        return render(request, template, context)

def transaction_list_view(request, month=None, year=None):
    transactions = Transaction.objects.by_month(year=year, month=month)
    template = 'oplaty/transaction-list-view.html'
    context = {
        "transactions":transactions,
        "month_name":calendar.month_name[int(month)],
        "month":month,
        "year":year,
        }
    return render(request, template, context)

def expense_create_view(request):
    form = ExpenseForm(request.POST or None)
    context = {
        "form":form,
        "from":request.GET.get("from"),
        }
    if form.is_valid():
        form.save()
        messages.success(request, "Expense successfully added.")
        previous_page = context["from"]
        if previous_page:
            return redirect(previous_page)
        context = {
            "form":ExpenseForm(),
            }
    template = "oplaty/expense-create-view.html"
    return render(request, template, context)

def expense_detail_view(request, id=None):
        obj = get_object_or_404(Expense, id=id)
        transactions = Transaction.objects.filter(expense=obj)
        print(transactions)
        context = {
            "expense":obj,
            "transactions":transactions,
            "from":request.GET.get("from"),
            }
        template = "oplaty/expense-detail-view.html"
        return render(request, template, context)

def expense_update_view(request, id=None):
    obj = get_object_or_404(Expense, id=id)
    form = ExpenseForm(request.POST or None, instance=obj)
    context = {
        "form":form,
        "from":request.GET.get("from")
        }
    if form.is_valid():
        form.save()
        messages.success(request, "Expense saved.")
        return redirect("oplaty:month-view", year=obj.due_date.year,
                                             month=obj.due_date.month)
    template = "oplaty/expense-update-view.html"
    return render(request, template, context)

def expense_delete_view(request, id=None):
        obj = get_object_or_404(Expense, id=id)
        if request.method == "POST":
            obj.delete()
            messages.success(request, "Expense successfully deleted.")
            return redirect("oplaty:month-view", year=obj.due_date.year,
                                                 month=obj.due_date.month)
        context = {
            "expense":obj,
            }
        template = "oplaty/expense-delete-view.html"
        return render(request, template, context)

def home_view(request):
    return redirect("oplaty:year-view", year=datetime.now().year)

def year_detail_view(request, year=None):
    expenses = Expense.objects.year_ordered(year=year)
    recurring = expenses["recurring"]
    non_recurring = expenses["non_recurring"]
    summaries = Expense.objects.year_summary_by_months(year=year)
    months_names = [calendar.month_name[i] for i in range(1, 13)]

    template = 'oplaty/year-view.html'
    context = {
        "summaries":summaries,
        "recurring":recurring,
        "non_recurring":non_recurring,
        "months_names":months_names,
        "year":year,
        }
    return render(request, template, context)


def month_detail_view(request, month=None, year=None):
    exps_month_summary = Expense.objects.month_summary(year=year, month=month)
    expenses = Expense.objects.month_ordered(year=year, month=month)
    transactions = Transaction.objects.by_month_binded(year=year, month=month)
    recurring_expenses = expenses["recurring"]
    non_recurring_expenses = expenses["non_recurring"]
    template = 'oplaty/month-view.html'
    context = {
        "from":request.GET.get("from"),

        "transactions":transactions,

        "recurring_expenses":recurring_expenses,
        "recurring_amount_sum":exps_month_summary["recurring_amount_sum"],
        "recurring_remaining_sum":exps_month_summary["recurring_remaining_sum"],
        "recurring_amount_paid_sum":exps_month_summary["recurring_amount_paid_sum"],

        "non_recurring_expenses":non_recurring_expenses,
        "non_recurring_amount_sum":exps_month_summary["non_recurring_amount_sum"],
        "non_recurring_remaining_sum":exps_month_summary["non_recurring_remaining_sum"],
        "non_recurring_amount_paid_sum":exps_month_summary["non_recurring_amount_paid_sum"],

        "total_amount_sum":exps_month_summary["total_amount_sum"],
        "total_remaining_sum":exps_month_summary["total_remaining_sum"],
        "total_amount_paid_sum":exps_month_summary["total_amount_paid_sum"],

        "month_name":calendar.month_name[int(month)],
        "month":month,
        "year":year,
        }
    return render(request, template, context)

oplaty/templates/oplaty/expense-delete-view.html
{% extends "oplaty/base.html" %}

<head>
  <title>{% block title %}Transatcion delete{% endblock title %}</title>
</head>

{% block content %}
<div class="container"  style="max-width: 800px;">
  <div class="row">
    <div class="col">
      <div class="card bg-light mb-3 mt-3 text-center">
        <h2 class="card-header">
          {{ expense.title }} {{ expense.due_date|date:"d.m.y" }}
          <a class="btn btn-success btn-sm" href="{% url 'oplaty:expense-update' expense.id %}">EDIT</a>
          <a class="btn btn-danger btn-sm" href="{% url 'oplaty:expense-delete' expense.id %}">DEL</a>
        </h2>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover">
              <tr>
                <td style="width:30%">Title</td>
                <td>{{ expense.title }}</td>
              </tr>
              <tr>
                <td>Due date</td>
                <td>{{ expense.due_date|date:"d.m.y" }}</td>
              </tr>
              <tr>
                <td>Amount</td>
                <td>{{ expense.amount }}</td>
              </tr>
              <tr>
                <td>Recurring</td>
                <td>
                  {% if expense.recurring %}
                    Yes
                  {% else %}
                    No
                  {% endif %}
                </td>
              </tr>
              <tr>
                <td>Description</td>
                <td>{{ expense.description }}</td>
              </tr>
            </table>
          </div>
          <h1>Are you sure you want to delete this Expense?</h1>
          <form method="POST" action="."> {% csrf_token %}
            <input type="submit" value="Yes" class="btn btn-secondary btn-sm">
            <a class="btn btn-secondary btn-sm" href="{% url 'oplaty:expense-detail' id=expense.id %}">No</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

oplaty/templates/oplaty/expense-detail-view.html
{% extends "oplaty/base.html" %}

<head>
  <title>{% block title %}Expense {{ expense.id }}{% endblock title %}</title>
</head>

{% block content %}
<div class="container"  style="max-width: 800px;">
  <div class="row">
    <div class="col">
      <div class="card bg-light mb-3 mt-3 text-center">
        <h2 class="card-header">
          {{ expense.title }} {{ expense.due_date|date:"d.m.y" }}
          <a class="btn btn-success btn-sm" href="{% url 'oplaty:expense-update' expense.id %}?from={{ request.path|urlencode }}">EDIT</a>
          <a class="btn btn-danger btn-sm" href="{% url 'oplaty:expense-delete' expense.id %}?from={{ request.path|urlencode }}">DEL</a>
        </h2>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover">
              <tr>
                <td style="width:30%">Title</td>
                <td>{{ expense.title }}</td>
              </tr>
              <tr>
                <td>Due date</td>
                <td>{{ expense.due_date|date:"d.m.y" }}</td>
              </tr>
              <tr>
                <td>Amount</td>
                <td>{{ expense.amount }}</td>
              </tr>
              <tr>
                <td>Recurring</td>
                <td>
                  {% if expense.recurring %}
                    Yes
                  {% else %}
                    No
                  {% endif %}
                </td>
              </tr>
              <tr>
                <td>Description</td>
                <td>{{ expense.description }}</td>
              </tr>
            </table>
            <h3 class="btn btn-secondary btn-lg btn-block mt-3">
              Transactions
              <a class="btn btn-secondary btn-sm badge-pill" href="{% url 'oplaty:transaction-create' %}?from={{ request.path|urlencode }}"><i class="fas fa-plus-circle"></i></a>
            </h3>
            <div class="table-responsive">
              <table class="table table-bordered table-striped table-hover">
                {% if transactions %}
                <thead>
                  <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Expense</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for transaction in transactions %}
                  <tr>
                    <td>
                      <a class="btn btn-secondary btn-sm btn-block" href="{% url 'oplaty:transaction-detail' transaction.id %}?from={{ request.path|urlencode }}">{{ transaction.date|date:"d.m.Y" }}</a>
                    </td>
                    <td>{{ transaction.amount}}</td>
                    <td>{{ transaction.expense.title }}</td>
                    <td>
                      <a class="btn btn-success btn-sm" href="{% url 'oplaty:transaction-update' transaction.id %}?from={{ request.path|urlencode }}">EDIT</a>
                      <a class="btn btn-danger btn-sm" href="{% url 'oplaty:transaction-delete' transaction.id %}?from={{ request.path|urlencode }}">DEL</a>
                    </td>
                  </tr>
                  {% endfor %}
                  {% else %}
                    <tr><td>No transactions</td></tr>
                  {% endif %}
                </tbody>
              </table>
            </div>
          </div>
          <a class="btn btn-secondary btn-sm" href="{% if from %}{{ from }}{% else %}{% url 'oplaty:month-view' month=expense.due_date.month year=expense.due_date.year %}{% endif %}">Back</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

oplaty/templates/oplaty/expense-update-view.html
{% extends "oplaty/base.html" %}
{% load crispy_forms_tags %}

<head>
  <title>{% block title %}{{ month_name }} {{ year }}{% endblock title %}</title>
</head>

{% block content %}
<div class="container"  style="max-width: 800px;">
  <div class="row">
    <div class="col">
      <div class="card bg-light mb-3 mt-3 text-center">
        <h2 class="card-header">
          Edit Expense
        </h2>
        <div class="card-body">
          <form method="post" action=".">{% csrf_token %}
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover">
              <tr>
                <td style="width:30%">Title</td>
                <td>{{ form.title|as_crispy_field }}</td>
              </tr>
              <tr>
                <td>Due date</td>
                <td>{{ form.due_date|as_crispy_field }}</td>
              </tr>
              <tr>
                <td>Amount</td>
                <td>{{ form.amount|as_crispy_field }}</td>
              </tr>
              <tr>
                <td>Recurring</td>
                <td>{{ form.recurring|as_crispy_field }}</td>
              </tr>
              <tr>
                <td>Description</td>
                <td>{{ form.description|as_crispy_field }}</td>
              </tr>
            </table>
            <input type="submit" value="Apply" class="btn btn-secondary btn-sm">
            <a class="btn btn-secondary btn-sm" href="{% url 'oplaty:expense-detail' id=form.instance.id %}">Cancel</a>
          </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

oplaty/templates/oplaty/month-view.html
{% extends "oplaty/base.html" %}

<head>
  <title>{% block title %}{{ month_name }} {{ year }}{% endblock title %}</title>
</head>

{% block content %}
<div class="container"  style="max-width: 800px;">
  <div class="row">
    <div class="col">
      <div class="card bg-light mb-3 mt-3 text-center">
        <h2 class="card-header">
          {{ month_name }} {{ year }}
          <div class="col">
            <a class="btn btn-secondary btn-sm" href="{% url 'oplaty:year-view' year=year %}">Year View</a>
            <a class="btn btn-secondary btn-sm" href="{% url 'oplaty:transaction-list' year=year month=month %}">Transactions View</a>
          </div>
        </h2>
        <div class="card-body">
          <h3 class="btn btn-secondary btn-lg btn-block">
            Expenses
            <a class="btn btn-secondary btn-sm badge-pill" href="{% url 'oplaty:expense-create' %}?from={{ request.path|urlencode }}">
              <i class="fas fa-plus-circle"></i>
            </a>
          </h3>
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover">
              {% if recurring_expenses or non_recurring_expenses %}
                <thead>
                  <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Due date</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Paid</th>
                    <th scope="col">Remaining</th>
                  </tr>
                </thead>
                <tbody>
                  {% if recurring_expenses %}
                    {% for expense in recurring_expenses %}
                      <tr data-toggle="collapse" data-target="#transaction-row-{{ expense.title }}" aria-expanded="false" aria-controls="transaction-row-{{ expense.title }}">
                        <td>
                          <a class="btn btn-secondary btn-sm btn-block" href="{% url 'oplaty:expense-detail' expense.id %}?from={{ request.path|urlencode }}">
                          {{ expense.title }}</a>
                        </td>
                        <td>{{ expense.due_date|date:"d.m.y" }}</td>
                        <td>{{ expense.amount}}</td>
                        <td>{{ expense.amount_paid }}</td>
                        <td>{{ expense.remaining_amount }}</td>
                      </tr>
                    {% endfor %}
                      <tr style="font-weight:bold">
                      <td align='center' colspan=2>Recurring</td>
                      <td>{{ recurring_amount_sum }}</td>
                      <td>{{ recurring_amount_paid_sum }}</td>
                      <td>{{ recurring_remaining_sum }}</td>
                    </tr>
                    <tr style="height: 30px;"></tr>
                  {% endif %}
                  {% if non_recurring_expenses %}
                    {% for expense in non_recurring_expenses %}
                      <tr data-toggle="collapse" data-target="#transaction-row-{{ expense.title }}" aria-expanded="false" aria-controls="transaction-row-{{ expense.title }}">
                        <td>
                          <a class="btn btn-secondary btn-sm btn-block" href="{% url 'oplaty:expense-detail' expense.id %}?from={{ request.path|urlencode }}">
                          {{ expense.title }}</a>
                        </td>
                        <td>{{ expense.due_date|date:"d.m.y" }}</td>
                        <td>{{ expense.amount}}</td>
                        <td>{{ expense.amount_paid }}</td>
                        <td>{{ expense.remaining_amount }}</td>
                      </tr>
                    {% endfor %}
                    <tr style="font-weight:bold">
                      <td align='center' colspan=2>Non-recurring</td>
                      <td>{{ non_recurring_amount_sum }}</td>
                      <td>{{ non_recurring_amount_paid_sum }}</td>
                      <td>{{ non_recurring_remaining_sum }}</td>
                    </tr>
                  <tr style="height: 30px;"></tr>
                  {% endif %}
                  {% if recurring_expenses and non_recurring_expenses %}
                    <tr style="font-weight:bold">
                      <td align='center' colspan=2>Total</td>
                      <td>{{ total_amount_sum }}</td>
                      <td>{{ total_amount_paid_sum }}</td>
                      <td>{{ total_remaining_sum }}</td>
                    </tr>
                    {% endif %}
                {% else %}
                    <tr><td>No expenses</td></tr>
                </tbody>
              {% endif %}
            </div>
            </table>
            <h3 class="btn btn-secondary btn-lg btn-block mt-3">
              Transactions
              <a class="btn btn-secondary btn-sm badge-pill" href="{% url 'oplaty:transaction-create' %}?from={{ request.path|urlencode }}"><i class="fas fa-plus-circle"></i></a>
            </h3>
            <div class="table-responsive">
              <table class="table table-bordered table-striped table-hover">
                {% if transactions %}
                <thead>
                  <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Expense</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for transaction in transactions %}
                  <tr>
                    <td>
                      <a class="btn btn-secondary btn-sm btn-block" href="{% url 'oplaty:transaction-detail' transaction.id %}?from={{ request.path|urlencode }}">{{ transaction.date|date:"d.m.Y" }}</a>
                    </td>
                    <td>{{ transaction.amount}}</td>
                    <td>{{ transaction.expense.title }}</td>
                    <td>
                      <a class="btn btn-success btn-sm" href="{% url 'oplaty:transaction-update' transaction.id %}?from={{ request.path|urlencode }}">EDIT</a>
                      <a class="btn btn-danger btn-sm" href="{% url 'oplaty:transaction-delete' transaction.id %}?from={{ request.path|urlencode }}">DEL</a>
                    </td>
                  </tr>
                  {% endfor %}
                  {% else %}
                    <tr><td>No transactions</td></tr>
                  {% endif %}
                </tbody>
              </table>
            </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock %}